version: "3"
services:
  metube:
    image: ghcr.io/amirulandalib/yt-dlp-web-ui:latest
    container_name: ytdlp-webui-go
    restart: unless-stopped
    ports:
      - "3033:3033"
    volumes:
      - "/home/amirulandalib/Downloads/ytdlp:/downloads"
    environment:
      - TZ=Asia/Dhaka
